### ISSUE TITLE
DynamicSurroundings config reset upon loading game

### ISSUE THREAD

**Issue by bkane2** [WesterosCraftCode/ElectronLauncher#4]
Config options for DynamicSurroundings don't appear to be persistent (in this case, disabling "Player Footprints"- each time I start the game these have been reset to being enabled).

**Comment by dscalzi** [comment]
This is because the md5 hash is listed on the distribution index. As a result, it is validated on startup. You can see this on the cached version stored in the repo.

https://github.com/WesterosCraftCode/ElectronLauncher/blob/master/app/assets/distribution.json#L292

I think this may also be the case on the old launcher, see https://bitbucket.org/westeroscraft/westeroscraftclientfiles/src/467fdc258b994310a4e0542de83988a068d736d0/westeroscraft.xml#lines-176

We can change this, however mike would need to sync the distro before it goes live.

**Comment by dscalzi** [comment]
I've removed the MD5 for dsurround.cfg ([58677d6](https://bitbucket.org/westeroscraft/westeroscraftclientfiles/commits/58677d670f2432a71edd04f6615c97a9b45d08ce)). This will be live when mike next syncs the index. I'll send him a message but he's been a bit MIA recently.

**Comment by dscalzi** [comment]
Appears it has been synced.
